name: Release Blade Old

on: [pull_request]
  # push:
  #   branches: [master]

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Setup Cache & Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile
      - name: Lint Source Code
        run: yarn lint
      - name: Run Web Tests
        run: yarn test:web
        working-directory: packages/blade-old
      - name: Run Native Tests
        run: yarn test:native
        working-directory: packages/blade-old
      - name: Copy .npmrc to packages/blade-old for publishing
        run: cp .npmrc packages/blade-old
      - name: Publish package
        run: |
          git config --global user.email "tools+cibot@razorpay.com"
          git config --global user.name "rzpcibot"
          yarn version:publish
        working-directory: packages/blade-old